# 因果推論の概要と共変量制御のアプローチ

ひとは誰しも「よりよい」と信じる方向へ進みたいものですが、現状を認識したら、その現状に対してどのような行動を取ればよいかを考えるでしょう。ここでは、「どのような選択をすればよいか」を考えるプログラム評価のための「統計的因果推論」について考えていきます。この因果推論においても、『未知の確率過程から生ずるデータを用いて、その過程のパラメータを推定する』という基本的考えは同じですが、『比較対象を設定する』という点において、今までの推定と決定的に異なっています。経済学者が長く取り組んできた問題であり、多くの手法・アプローチが考案されてきました。歴史や実例に触れながら、その発想法について2回の講義を通じて考えていきましょう。

> 1. 潜在的結果と反実仮想にもとづく因果推論
> 2. 選択効果から処置効果を分別するための識別条件
> 3. 観測可能な共変量・属性による「マッチング」
> 4. 時間を通じて安定した属性を制御する「固定効果」

---

__1. 潜在的結果と反実仮想にもとづく因果推論__

<iframe src="https://player.vimeo.com/video/573851269?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="506" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="潜在的結果と反実仮想にもとづく因果推論"></iframe>

> 要点

- 因果効果$\tau_i$(=諸条件($X$)を一定とした上で、処置($D$)を変えたときに生じる結果($Y$)の差)を考えるためには、比較対象を適切に設定しなくてはいけない
- 潜在的結果$\{Y^T_i, Y^C_i\}$は、処置の選択$\{T,C\}$によって「事前的に観測しうる」(a pri ori observable)結果である。このとき、$i$における因果効果とは

$$
\tau_i =Y^T_i - Y^C_i
$$

- 事後的には、潜在的結果のうち事実(factual)のみしか観察できず、観測できない結果を反実仮想(counterfactual)と呼ぶ。すなわち、因果効果を推定するとは、すなわち反実仮想を推測することである

---

__2. 選択効果から処置効果を分別するための識別条件__

<iframe src="https://player.vimeo.com/video/573848939?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="506" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="選択効果から処置効果を分別するための識別条件"></iframe>

> 要点

- 因果効果の推定を、『反実仮想という比較対象の設定問題/ 欠測値の穴埋め問題』と捉えることができる
  - 「主観的」 ... 事前信念を用いて、$N=1$でも学習する
  - 「より客観的」... 個人ではなく集団について、条件付期待値を推定する

- 処置効果 = 観測される「処置群」と「比較群」の差 - 選択効果
  $$
  \underset{=\mathbb{E}\left[\tau_{i}|T\right] (処置効果)}{\underbrace{\mathbb{E}\left[Y_{i}^{T}|T\right]-\mathbb{E}\left[Y_{i}^{C}|T\right]}} = \underset{=\text{観察される差}}{\underbrace{\mathbb{E}\left[Y_{i}^{T}|T\right]-\mathbb{E}\left[Y_{i}^{C}|C\right]}}-\underset{=\text{選択効果}}{\underbrace{(\mathbb{E}\left[Y_{i}^{C}|T\right]-\mathbb{E}\left[Y_{i}^{C}|C\right])}}
  $$
**補足:** 処置を受けた人への効果は、Treatment on Treated (ToT)だけでなく、Average Treatment on Treated (ATT)とも呼ばれる。

- 「主観的」... 選択効果を他の情報から吟味する(事例研究など)
- 「より客観的」... 選択効果を除去するような条件(識別条件)を満たすときを見つける
  (1) 共変量を用いて、観測できる交絡因子を制御する
  (2) 時系列の処置の変化を用いて、安定している交絡因子を制御する
  (3) 処置の可能性が無作為になっているような状況を用いて、ほぼ全ての交絡因子を制御する
  識別条件が厳しい状況の方がより信頼できるが、より難しい
  
  **補足:**識別条件の仮定を、データのみから完全に吟味することはできない。
  
  ---
  
__3. 観測できる共変量・属性による「マッチング」__

  <iframe src="https://player.vimeo.com/video/574762482?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="506" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="観測できる共変量・属性による「マッチング」"></iframe>
  
> 要点

- 「マッチング」＝似ているもの同士でペアを組み、比較をすること
- 重回帰分析で共変量を制御することも、「マッチング」として捉えることができ、制御しきれない交絡因子によって生じる選択効果を欠落変数バイアスとして捉えることができる

- 重回帰分析における識別条件:
$$
  \mathbb{E}[Y^C|C,X] = \mathbb{E}[Y^C|T,X]
  $$
- 共変量を含めるかどうかの指針
  (1) 交絡因子である場合 ... Yes
  (2) 媒介因子である場合 ... No
  (3) 測定誤差を減らせる独立因子である場合 ... 基本的にYes
  (4) 全く関係のない因子である場合 ... No
  どの共変量を含めたらよいか、必ずしも分からないため、様々な共変量を入れて試す「感度分析」が大切である

**訂正:** 

- 重回帰の3次元の図における$\beta_0$は、切片ではなく、$D=0$の平面かつ回帰平面上の$X=0$となっている点である。

- 欠落変数バイアスの公式における選択効果の項は、$Cov(D_i, X_i)/Var(X_i) \gamma$ではなく、$Cov(D_i, X_i)/Var(D_i) \gamma$である

---
  
  __4. 時間を通じて安定した属性を制御する「固定効果」__

  <iframe src="https://player.vimeo.com/video/574760270?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="506" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="時間を通じて安定した属性を制御する「固定効果」"></iframe>


> 要点

- 固定効果モデルでは、共変量として、ダミー変数$f_i$を含める
$$
  Y_{it} = \beta_1 D_{it} + f_i + \varepsilon_{it}
  $$
  
  - 通常のOLSでは$i$の間のパターンを捉えるのに対し、固定効果モデルでは$i$の内のパターンを捉えることとなる

- 固定効果分析における識別条件: 全ての時点$t,s$において

$$
  \mathbb{E}[Y_{it}^C|C_{is}] = \mathbb{E}[Y_{it}^C|T_{is}]
  $$
  
  ---

__参考図書・文献__

William Shadish, Thomas Cook, and Donald Campbell "Experimental and Quasi-Experimental Designs for Generalized Causal Inference." *Houghton Mifflin Company.* 2002.

Joshua Angrist and Jorn-Steffen Pischke "Mostly Harmless Econometrics: An Empiricist's Companion", *Princeton University Press*, 2009

Guido Imbens and Donald Rubin "Causal Inference for Statistics, Social, and Biomedical Sciences: An Introduction", *Cambridge University Press*, 2015

Judea Pearl and Dana MacKenzie "The Book of Why: The New Science of Cause and Effect" *Penguine Books*, 2019

西山慶彦・新谷元嗣・川口大司・奥井亮『計量経済学 Econometrics: Statistical Data Analysis for Empirical Economics』New Liberal Arts Selection、 有斐閣、2019年

伊藤公一朗 『データ分析の力　因果関係に迫る思考法』光文社新書、2017年

中室牧子、津川友介 『「原因と結果」の経済学　データから真実を見抜く思考法』ダイヤモンド社、2017年

安井翔太・株式会社ホクソエム 『効果検証入門　正しい比較のための因果推論/計量経済学の基礎』 技術評論社、2020年

佐藤俊樹 『社会科学と因果分析　ウェーバーの方法論から知の現在へ』岩波書店、2019年

Esther Duflo, Rachel Glennester, Michael Kremer　『政策評価のための因果関係の見つけ方　ランダム化比較試験入門』小林庸平監訳、日本評論社、2019年

